# Generated by Django 2.1.1 on 2018-10-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurroApp', '0003_house_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='frequency',
            field=models.CharField(choices=[('Option 1', 'Daily'), ('Option 2', 'Weekly'), ('Option 3', 'Fortnightly'), ('Option 4', 'Monthly'), ('Option 5', 'Quarterly'), ('Option 6', 'Yearly')], max_length=50),
        ),
    ]
