# Generated by Django 2.1.1 on 2018-10-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurroApp', '0008_auto_20181014_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills_share',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='bills_share',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_split',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_split',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Bills_Share',
        ),
    ]
