# Generated by Django 2.1.1 on 2018-10-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurroApp', '0009_auto_20181014_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_item',
            name='done',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='chore',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ONCEOFF', 'Once Off')], max_length=20),
        ),
    ]
