# Generated by Django 2.1.1 on 2018-10-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChurroApp', '0011_auto_20181017_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='description',
        ),
    ]
