# Generated by Django 2.1.1 on 2018-10-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurroApp', '0012_remove_reminder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ONCEOFF', 'Once Off')], default='Weekly', max_length=20),
        ),
    ]
